### ISSUE TITLE
Initializing a bitstring from a NamedTemporaryFile doesn't work correctly.

### ISSUE THREAD

**Issue by andrew-vant** [scott-griffiths/bitstring#151]
I'm initializing a bitstring from a NamedTemporaryFile and getting unexpected behavior. It seems to create a one-bit bitstring, instead of using whatever was actually in the file. The problem is fairly easy to reproduce:

```python
#!/usr/bin/python3
import tempfile, bitstring
from io import IOBase as file # important later

# Create some dummy data
ntf = tempfile.NamedTemporaryFile()
ntf.write(b'FF')
f = open(ntf.name, "rb")

# Creating a bitstring from each gets different results
ntf.seek(0)
print(bitstring.Bits(ntf).bin) # 1
f.seek(0)
print(bitstring.Bits(f).bin)   # 0100011001000110

# Just to demonstrate that the two really are the same file:
ntf.seek(0)
print(ntf.read()) # b'FF'
f.seek(0)
print(f.read())   # b'FF'
```

I note that _setauto checks if something is a file object with isinstance(s, file), where file is an alias for IOBase; but NamedTemporaryFile doesn't seem to inherit from IOBase:

```python
print(isinstance(ntf, file)) # False
print(isinstance(f, file)) # True
```

So I'm guessing auto is identifying my NTF as something other than a file (no idea what exactly), and as far as I can tell there is no explicit file-object initializer (feature request?). I can work around that, but I'm pretty sure it's not intended behavior.

**Comment by scott-griffiths** [comment]
I don't think that there is a bug here. The problem is that the NamedTemporaryFile isn't a file, and so doesn't get opened as such. It would be nice if tempfile could be changed so that the objects it creates were file instances, but that's a bug/feature request for that module.

I could add support for tempfile so that it adds a check for its types, but I don't think that would help many people, plus it would generate a new dependency and testing overhead so I'm not keen.
