### ISSUE TITLE
Creation from array.array

### ISSUE THREAD

**Issue by p0lm** [scott-griffiths/bitstring#153]
It'd be nice to have support for creation from array.array objects too. As it is, no error is thrown upon passing in an array.array, though initialization is flawed.

**Comment by scott-griffiths** [comment]
Thanks for the suggestion. The array should be being interpreted in the same way as a list of values, so that each value is converted to a single bit depending on whether it it 'True' in the boolean sense (so I don't think the current behaviour is a bug - please correct me if you think otherwise). But this is probably not the most useful thing to do.

I think a conversion using all of the bits stored in the array should be unambiguous, and I doubt anyone is relying on the current array initialisation, so this is a reasonable feature request and I'll look into it when I get back on to this project.

**Comment by p0lm** [comment]
Ah, I see what you mean. If interpreted as a list, it does indeed initialize on truth values. Still, it is somewhat counter-intuitive right now.

**Comment by scott-griffiths** [comment]
Done in 3.1.5.
