### ISSUE TITLE
Find indices of zeros or ones

### ISSUE THREAD

**Issue by tsoernes** [scott-griffiths/bitstring#175]
I have a feature request for something equivalent to this:
```
import numpy as np
from bitstring import BitArray

cellstate_np = np.random.choice([0, 1], size=(10)).astype(bool)
cellstate = BitArray(cellstate_np)


def where(bits, val):
    idxs = []
    for i in range(bits.len):
        if ((bits[0] == val)):
            idxs.append(i)
        bits = bits << 1
    return idxs


print(cellstate.bin)
print(where(cellstate, True))
```
The code works as expected, but there's probably a faster way to do things under the hood.

**Comment by scott-griffiths** [comment]
I strongly suspect that you don't even need the `where`  method, and whatever it is you are using the list created by the `where`, you should just be iterating over the `BitArray `and not worrying about any indices. Creating a list of indices looks like the wrong approach to most problems I can think of.

Also, modifying the `bits` and only looking at the first index each time is hideously more expensive than just iterating over all the bit positions.

So instead of 

    for i in where(cellstate, True):
        do_something(i)

you should just use

    for i in cellstate: 
        if i: 
            do_something(i)
