### ISSUE TITLE
Unexpected ByteArray.findall behavior with byte literals

### ISSUE THREAD

**Issue by Datamance** [scott-griffiths/bitstring#188]
Observe:

```python
>>> first_bit_set = bitstring.BitArray(length=16)
>>> first_bit_set.bin
'0000000000000000'
>>> first_bit_set[0] = 1
>>> first_bit_set.bin
'1000000000000000'
>>> # Now the first bit is actually set
>>> list(first_bit_set.findall('0b1'))  # expected behavior
[0]
>>> list(first_bit_set.findall(0b1))  # odd byte literal behavior
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
>>> list(first_bit_set.findall(0b01))  # odd byte literal behavior, no matter how we pad
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
```

Weird that the string arg works perfectly fine, but the byte literal produces the inverse result.

**Comment by scott-griffiths** [comment]
Yes that does look weird, but it's intended behaviour (or at least unavoidable behaviour).

The issue is that 0b1 and 0b01 are both Python integers equal to 1 and there is no way even in principle to distinguish between them. (Try `0b01 is 1` on the Python command line).

So what you are saying is `.findall(1)` which has to construct a bitstring from an integer. When it does this the defined behaviour is to create a bitstring of the integer's length initialised to all zeros. So `BitArray(1)` is actually a zero bit!

There's no way around this although it can be unintuitive. For comparison if you use the in-built `bytearray(n)` it generates `n` zero bytes.

So you need to use `'0b01'` or `[0, 1]` instead of `0b01`.
