### ISSUE TITLE
Python Versions

### ISSUE THREAD

**Issue by gasparmedina** [scott-griffiths/bitstring#192]
Hello, I am trying to use this library with the version of python 3.7 and I am getting the following error
    
from bitstring import BitArray
ModuleNotFoundError: No module named 'bitstring'

I am importing the library correctly, because when I use python 3.5 it works.

I would like to know if there is any alternative way to use this library in the latest version of python?

**Comment by scott-griffiths** [comment]
Hi, not sure what the problem is but there shouldn't be any major difference in 3.7 (though I'm still using 3.6 mostly).

Error suggests it just hasn't been installed for 3.7. If it's a virtualenv then make sure you do the pip install after activating it. Or if it's not a virtualenv then try 'python3.7 -m pip install bitstring' (or whichever version of Python you are using) to make sure it installs it for the correct one.

Let me know if you still have issues.

**Comment by gasparmedina** [comment]
This is not a bitstring problem, because I used it in a project from scratch and it worked with python 3.7. The problem was another one when I tried to use this with a cryptography library that had other dependencies. Thank you!
