### ISSUE TITLE
How do I manipulate data read from file (BitArray versus ConstBitStream)

### ISSUE THREAD

**Issue by TracyWel** [scott-griffiths/bitstring#200]
I'm trying to read data from a large binary file, do some operations on it and write to output. I don't want the whole thing read into memory, so I gather that I should not use BitArray to connect to the file.

I keep getting errors. I assume it's because I'm trying to change immutable data(?)

What is the correct way to do this?

Here's some code

(test of byteswap on BitArray - works fine)
a = BitArray('0b0100011100000010')
print(a.bin)
a.byteswap()
print(a.bin)

(test on BitStream)
s = ConstBitStream(filename = "file.RAW")
a = s.read('bin:16')
print(a)
(tried copying BitStream data into BitArray - no joy)
b = BitArray('0b0000000000000000')
print(b.bin)
b = a[0:16]
print(b)
b.byteswap()
print(b)

(keep getting an error for this byteswap - AttributeError: 'str' object has no attribute 'bin')

**Comment by scott-griffiths** [comment]
When you read 'bin:16', it reads 16 bits and converts to a binary string. So it returns an ordinary Python string, which is why you can't call bitstring methods on it.

You want to just use `s.read(16)`, which will give a ConstBitStream object of length 16 bits back.

So something like:

a = BitArray(s.read(16))  # read 16 bits and put in a mutable BitArray
a.byteswap()

should work for you.

**Comment by TracyWel** [comment]
Awesome! Thank you
