### ISSUE TITLE
How do I perform Bit-wise operations on lists of BitArrays ?

### ISSUE THREAD

**Issue by rf987** [scott-griffiths/bitstring#202]
Thanks for the great library.   

I know I can peform a bitwise AND by doing:
`(bit_array1&bit_array2)`

But what if I have a list of BitArrays, and the list is an unknown length.  How can I use Bitstring library to calculate the bitwise AND of all BitArrays in the list ?

For example, with the built-in python sets, I can calculate the intersection of a list of sets by doing:  

`set.intersection(*list_of_sets)`

Is there a way to do something like this with bitstring ?

**Comment by scott-griffiths** [comment]
Hi,

I'm not sure I understand the question. The bitwise AND is only defined for bitstrings of equal length. If they are of different lengths then you will need to pad them to be the same length (up to you whether you pad on the right or left - which is why it's not done automatically).

If they are already the same length then you can just AND them all in the normal way, for example:

import functools
functools.reduce(lamda a, b: a&b, bit_array_list)
