### ISSUE TITLE
reading files with different endianness

### ISSUE THREAD

**Issue by mexanick** [scott-griffiths/bitstring#204]
Hi Scott,
Could you please consider to add an endianness specifier when reading a bitstream from file?
I find your lib great, but my data is not aligned to bytes and I have to use such ugly constructions as 
```python
from bitstring import ConstBitStream
cbs = ConstBitStream(filename='./test_data.dat')
word = cbs.read('uintle:64')
bitword = ConstBitStream(uint = word, length = 64)
vals = bitword.readlist('uint:4, uint:4, uint:24, uint:12, uint:12, uint:8')
```

**Comment by scott-griffiths** [comment]
Hi. Sorry for the delay in replying.

I see your point about it being rather ugly (and wasteful), but I'm not sure what the alternative could or should be.

The call to `readlist` only works because the little-endianness of the containing 8 bytes is already known. The best I can think of is to have something like a `readlist_le` method, but that would only work if an integer number of bytes was being read, and I don't think it would be very clear what was happening.

You could do something like:

```
word = BitStream(cbs.read(64))
word.byteswap()
vals = word.readlist('uint:4, uint:4, uint:24, uint:12, uint:12, uint:8')
```

which I think better expresses the process and doesn't go via an integer intermediate value.
